var ose = {
    'OSETT_INT32' : 105,
    'OSETT_FLOAT' : 102,
    'OSETT_STRING' : 115,
    'OSETT_BLOB' : 98,
    'OSETT_TRUE' : 84,
    'OSETT_FALSE' : 70,
    'OSETT_ID' : 44,
    'OSETT_BUNDLE' : 124,
    'OSETT_MESSAGE' : 45,
    
    'pushInt32' : Module.cwrap('ose_pushInt32', null, ['number', 'number']),
    'pushFloat' : Module.cwrap('ose_pushFloat', null, ['number', 'number']),
    'pushString' : Module.cwrap('ose_pushString', null, ['number', 'string']),
    'pushBlob' : Module.cwrap('ose_pushBlob', null, ['number', 'number', 'number']),
    'peekAddress' : Module.cwrap('ose_peekAddress', 'string', ['number']),
    'peekAddress' : Module.cwrap('ose_peekAddress', 'number', ['number']),
    'peekInt32' : Module.cwrap('ose_peekInt32', 'number', ['number']),
    'peekFloat' : Module.cwrap('ose_peekFloat', 'number', ['number']),
    'peekString' : Module.cwrap('ose_peekString', 'string', ['number']),
    'peekBlob' : Module.cwrap('ose_peekBlob', 'number', ['number']),
    'popInt32' : Module.cwrap('ose_popInt32', 'number', ['number']),
    'popFloat' : Module.cwrap('ose_popFloat', 'number', ['number']),
    // 'popString' : Module.cwrap('ose_popString', 'string', ['number']),
    // 'popBlob' : Module.cwrap('ose_popBlob', 'number', ['number']),
    'withPoppedString' : (bundle, fn, context)=>{
    	let str = Module.ccall('osejs_popString', 'string', ['number'], [bundle]);
	let ret = fn(str, context);
	Module._free(str);
	return ret;
    },
    'withPoppedBlob' : (bundle, fn, context)=>{
    	let str = Module.ccall('osejs_popBlob', 'number', ['number'], [bundle]);
	let ret = fn(str, context);
	Module._free(str);
	return ret;
    },

    'ose_2drop' : Module.cwrap('ose_2drop', null, ['number']),
    'ose_2dup' : Module.cwrap('ose_2dup', null, ['number']),
    'ose_2over' : Module.cwrap('ose_2over', null, ['number']),
    'ose_2swap' : Module.cwrap('ose_2swap', null, ['number']),
    'ose_drop' : Module.cwrap('ose_drop', null, ['number']),
    'ose_dup' : Module.cwrap('ose_dup', null, ['number']),
    'ose_nip' : Module.cwrap('ose_nip', null, ['number']),
    'ose_notrot' : Module.cwrap('ose_notrot', null, ['number']),
    'ose_over' : Module.cwrap('ose_over', null, ['number']),
    'ose_pick' : Module.cwrap('ose_pick', null, ['number']),
    'ose_pickBottom' : Module.cwrap('ose_pickBottom', null, ['number']),
    'ose_pickMatch' : Module.cwrap('ose_pickMatch', null, ['number']),
    'ose_roll' : Module.cwrap('ose_roll', null, ['number']),
    'ose_rollBottom' : Module.cwrap('ose_rollBottom', null, ['number']),
    'ose_rollMatch' : Module.cwrap('ose_rollMatch', null, ['number']),
    'ose_rot' : Module.cwrap('ose_rot', null, ['number']),
    'ose_swap' : Module.cwrap('ose_swap', null, ['number']),
    'ose_tuck' : Module.cwrap('ose_tuck', null, ['number']),

    'ose_bundleAll' : Module.cwrap('ose_bundleAll', null, ['number']),
    'ose_bundleFromBottom' : Module.cwrap('ose_bundleFromBottom', null, ['number']),
    'ose_bundleFromTop' : Module.cwrap('ose_bundleFromTop', null, ['number']),
    'ose_clear' : Module.cwrap('ose_clear', null, ['number']),
    'ose_clearPayload' : Module.cwrap('ose_clearPayload', null, ['number']),
    'ose_pop' : Module.cwrap('ose_pop', null, ['number']),
    'ose_popAll' : Module.cwrap('ose_popAll', null, ['number']),
    'ose_popAllDrop' : Module.cwrap('ose_popAllDrop', null, ['number']),
    'ose_popAllBundle' : Module.cwrap('ose_popAllBundle', null, ['number']),
    'ose_popAllDropBundle' : Module.cwrap('ose_popAllDropBundle', null, ['number']),
    'ose_push' : Module.cwrap('ose_push', null, ['number']),
    'ose_unpack' : Module.cwrap('ose_unpack', null, ['number']),
    'ose_unpackDrop' : Module.cwrap('ose_unpackDrop', null, ['number']),
    'ose_unpackBundle' : Module.cwrap('ose_unpackBundle', null, ['number']),
    'ose_unpackDropBundle' : Module.cwrap('ose_unpackDropBundle', null, ['number']),

    'ose_countElems' : Module.cwrap('ose_countElems', null, ['number']),
    'ose_countItems' : Module.cwrap('ose_countItems', null, ['number']),
    'ose_lengthAddress' : Module.cwrap('ose_lengthAddress', null, ['number']),
    'ose_lengthTT' : Module.cwrap('ose_lengthTT', null, ['number']),
    'ose_lengthItem' : Module.cwrap('ose_lengthItem', null, ['number']),
    'ose_lengthsItems' : Module.cwrap('ose_lengthsItems', null, ['number']),
    'ose_sizeAddress' : Module.cwrap('ose_sizeAddress', null, ['number']),
    'ose_sizeElem' : Module.cwrap('ose_sizeElem', null, ['number']),
    'ose_sizeItem' : Module.cwrap('ose_sizeItem', null, ['number']),
    'ose_sizePayload' : Module.cwrap('ose_sizePayload', null, ['number']),
    'ose_sizesElems' : Module.cwrap('ose_sizesElems', null, ['number']),
    'ose_sizesItems' : Module.cwrap('ose_sizesItems', null, ['number']),
    'ose_sizeTT' : Module.cwrap('ose_sizeTT', null, ['number']),

    'ose_blobToElem' : Module.cwrap('ose_blobToElem', null, ['number']),
    'ose_blobToType' : Module.cwrap('ose_blobToType', null, ['number']),
    'ose_concatenateBlobs' : Module.cwrap('ose_concatenateBlobs', null, ['number']),
    'ose_concatenateStrings' : Module.cwrap('ose_concatenateStrings', null, ['number']),
    'ose_copyAddressToString' : Module.cwrap('ose_copyAddressToString', null, ['number']),
    'ose_copyPayloadToBlob' : Module.cwrap('ose_copyPayloadToBlob', null, ['number']),
    'ose_swapStringToAddress' : Module.cwrap('ose_swapStringToAddress', null, ['number']),
    'ose_copyTTToBlob' : Module.cwrap('ose_copyTTToBlob', null, ['number']),
    'ose_decatenateBlob' : Module.cwrap('ose_decatenateBlob', null, ['number']),
    'ose_decatenateString' : Module.cwrap('ose_decatenateString', null, ['number']),
    'ose_elemToBlob' : Module.cwrap('ose_elemToBlob', null, ['number']),
    'ose_itemToBlob' : Module.cwrap('ose_itemToBlob', null, ['number']),
    'ose_joinBlobs' : Module.cwrap('ose_joinBlobs', null, ['number']),
    'ose_joinStrings' : Module.cwrap('ose_joinStrings', null, ['number']),
    'ose_moveStringToAddress' : Module.cwrap('ose_moveStringToAddress', null, ['number']),
    'ose_splitBlobFromEnd' : Module.cwrap('ose_splitBlobFromEnd', null, ['number']),
    'ose_splitBlobFromStart' : Module.cwrap('ose_splitBlobFromStart', null, ['number']),
    'ose_splitStringFromEnd' : Module.cwrap('ose_splitStringFromEnd', null, ['number']),
    'ose_splitStringFromStart' : Module.cwrap('ose_splitStringFromStart', null, ['number']),
    'ose_swap4Bytes' : Module.cwrap('ose_swap4Bytes', null, ['number']),
    'ose_swap8Bytes' : Module.cwrap('ose_swap8Bytes', null, ['number']),
    'ose_swapNBytes' : Module.cwrap('ose_swapNBytes', null, ['number']),
    'ose_trimBlob' : Module.cwrap('ose_trimBlob', null, ['number']),
    'ose_trimString' : Module.cwrap('ose_trimString', null, ['number']),
    'ose_match' : Module.cwrap('ose_match', null, ['number']),
    'ose_pmatch' : Module.cwrap('ose_pmatch', null, ['number']),

    'ose_makeBlob' : Module.cwrap('ose_makeBlob', null, ['number']),
    'ose_pushBundle' : Module.cwrap('ose_pushBundle', null, ['number']),

    'ose_add' : Module.cwrap('ose_add', null, ['number']),
    'ose_sub' : Module.cwrap('ose_sub', null, ['number']),
    'ose_mul' : Module.cwrap('ose_mul', null, ['number']),
    'ose_div' : Module.cwrap('ose_div', null, ['number']),
    'ose_mod' : Module.cwrap('ose_mod', null, ['number']),
    'ose_neg' : Module.cwrap('ose_neg', null, ['number']),
    'ose_eql' : Module.cwrap('ose_eql', null, ['number']),
    'ose_lte' : Module.cwrap('ose_lte', null, ['number']),
    'ose_lt' : Module.cwrap('ose_lt', null, ['number']),
    'ose_and' : Module.cwrap('ose_and', null, ['number']),
    'ose_or' : Module.cwrap('ose_or', null, ['number']),

    'pprintBundle' : Module.cwrap('osejs_pprintBundle', null, ['number']),
};

var osevm = {
    'vm' : Module.cwrap('osevm', 'number'),
    'input' : Module.cwrap('vm_i', 'number'),
    'stack' : Module.cwrap('vm_s', 'number'),
    'env' : Module.cwrap('vm_e', 'number'),
    'control' : Module.cwrap('vm_c', 'number'),
    'dump' : Module.cwrap('vm_d', 'number'),
    'output' : Module.cwrap('vm_o', 'number'),
    'run' : Module.cwrap('osevm_run', null, ['number']),
};
